### ISSUE TITLE
Windows works

### ISSUE THREAD

**Issue by fietronic** [ReclaimYourPrivacy/eschalot#1]
![2015-06-05 05_47_38-_cygdrive_c_sg_eschalot-master](https://cloud.githubusercontent.com/assets/5356864/8004602/a8cb66ba-0b46-11e5-974f-755a4e80901d.png)
Not an issue but I thought I'd mention I was easily able to compile it for windows through cygwin. Not sure if the warnings are anything to be concerned about. Seems to function though.

**Comment by lbthomsen** [comment]
Great :)

**Comment by lbthomsen** [comment]
Another option on Windows would be running it through Docker.  Changes to this source trigger an automatic docker container generation over on Dockerhub.
