### ISSUE TITLE
temporary file for current hash

### ISSUE THREAD

**Issue by ghost** [ReclaimYourPrivacy/eschalot#14]
Imho, needs to create a temporary file for saving current state. It needs if computer rebooted (for example) for continue calculate.

**Comment by lbthomsen** [comment]
I haven't really done the math but I don't think it would make sense.  .onion addresses are 80 bits, so there are something along the line of 1x10^24 different combinations.  Eschalot does not make a systematic approach but rather a random one (afaik), so storing the hashes tried already would require an enormous database.

But well - the source is there so feel free to fork and try it out.

**Comment by harlyh** [comment]
I can confirm. It absolutely makes no sense. You will be dead way before eschalot could go through all combinations :)

**Comment by lbthomsen** [comment]
I'll close this one.
