### ISSUE TITLE
 [Miller-Rabin primality test] Public exponent ??

### ISSUE THREAD

**Issue by kenkit** [ReclaimYourPrivacy/eschalot#21]
Is there a way to enforce that all private keys have a prime number on the public exponent.
I've read somewhere that keys that don't pass the test are deemed weak.

**Comment by ghost** [comment]
As far I known, `e` only has to be prime with ` p-1` and `q-1`, which seems to be handled in the code at https://github.com/ReclaimYourPrivacy/eschalot/blob/master/eschalot.c#L490 (I did not review the check, only made sure it was present). So it doesn't even need to be prime. 

Can you share the link where you read it?

**Comment by kenkit** [comment]
[https://stackoverflow.com/questions/26462355/tips-to-generate-strong-rsa-keys](https://stackoverflow.com/questions/26462355/tips-to-generate-strong-rsa-keys)
[https://vanitydns.github.io/](https://vanitydns.github.io/)
Vanitydns is where I first saw this.

[https://people.csail.mit.edu/rivest/pubs/RS01.version-1999-11-22.pdf
](https://people.csail.mit.edu/rivest/pubs/RS01.version-1999-11-22.pdf)

**Comment by kenkit** [comment]
I use eschalot to generate keys +some backend crpyptopp to verify keys on my site, which i'm still working on.
You can open and check the page here [flamyop4nnz27qnu Onion](http://flamyop4nnz27qnu.onion/test ), in there try and paste any key you can generate using eschalot, then check the results you get from it, using The code found [http://www.sanfoundry.com/cpp-program-implement-miller-rabin-primality-test/](http://www.sanfoundry.com/cpp-program-implement-miller-rabin-primality-test/)
Not sure if I may have messed in my cryptopp implemention(keycheck).
I will disable the public api eventuall or make my custom eschalot that prevents users from snooping on generated keys.

**Comment by kenkit** [comment]
My main target is to offer secure and quality services to any clients that comes by, I would be willing to work with anyone who can help me achieve my objective even if I'm not such an experienced dev, so if you are free/willing, maybe we can work on this idea and make some coffee as time goes by.
I'm planning on using web-sockets for communication between the server and miner, that's if I will allow the public  compute power to continue as a service, also am planning on adding support to v3 onion address and use a clearnet domain.
My main objective is to lead in this field as there aren't many to challange the service currently

**Comment by ghost** [comment]
> https://stackoverflow.com/questions/26462355/tips-to-generate-strong-rsa-keys

Nothing about exponents in this post, only prime factors. CTRL+F'ed in https://people.csail.mit.edu/rivest/pubs/RS01.version-1999-11-22.pdf and it seems to be on the same subject.

>  https://vanitydns.github.io/

Sounds like a sales pitch to me , [since we can see that `Shallot` is making sure that `e` is co-prime with `lambda(n)`](https://github.com/katmagic/Shallot/blob/831de01b13b309933d32efe8388444ef6a831cfb/src/math.c#L72). Just as `eschalot`. 

In `libgcrypt`, [the following code checks the same thing (`cipher/rsa.c`)](https://github.com/gpg/libgcrypt/blob/master/cipher/rsa.c#L184):

```
[...] Returns 0 if the test has been passed. */
static int
check_exponent (void *arg, gcry_mpi_t a)
{
  mpi_sub_ui (a, a, 1);
  tmp = _gcry_mpi_alloc_like (a);
  result = !mpi_gcd(tmp, e, a); /* GCD is not 1. */
  _gcry_mpi_release (tmp);
[...]
          p = _gcry_generate_secret_prime (nbits/2, random_level,
                                           check_exponent, e);
          q = _gcry_generate_secret_prime (nbits/2, random_level,
                                           check_exponent, e);
```

> You can open and check the page here flamyop4nnz27qnu Onion, in there try and paste any key you can generate using eschalot, then check the results you get from it

The primality test should be performed against `p` and `q`, not `e`. Maybe you are mixing notions of public exponent and public modulus?

> also am planning on adding support to v3 onion address and use a clearnet domain.

\o

**Comment by kenkit** [comment]
Thank you for clarifying that, It had me worried abit, but am now going to work on the v3 onion address after doing some research on the same.
I've also come accross [https://github.com/cathugger/mkp224o](https://github.com/cathugger/mkp224o) and am planning to use this to add support for Tor v3 address,
I still hope that you will add support for Tor v3 onion address sometime when you are free.
Again, Thanks big for your time.
:)

**Comment by ghost** [comment]
Why not directly using these projects?

**Comment by kenkit** [comment]
sorry I didn't clearly say this, I came across https://github.com/cathugger/mkp224o  I hope it won't give me a hard time to integrate it alongside eschalot.
