### ISSUE TITLE
Make error: cannot find -lssl

### ISSUE THREAD

**Issue by owocean** [ReclaimYourPrivacy/eschalot#31]
![image](https://user-images.githubusercontent.com/43656163/64563090-0d73a480-d314-11e9-8b9b-6dd2aab890b3.png)

Im not sure what im missing. Any help would be very appreciated.

**Comment by lbthomsen** [comment]
Well - you need the libssl headers.  Probably "libssl-dev".  I think that will take care of the crypto too.

**Comment by zgruza** [comment]
Yep, need to get package libssl-dev. 👍

**Comment by owocean** [comment]
bruh its been 3 years lmao
i didnt even know this was open. that most likely solved the issue! ty
