### ISSUE TITLE
eschalot.c:66:10: fatal error: openssl/bn.h: No such file or directory

### ISSUE THREAD

**Issue by Spl01ter** [ReclaimYourPrivacy/eschalot#37]
pi@raspberrypi:~/eschalot $ make
cc -std=c99 -O2 -fPIC -finline-functions -Wall -W -Wunused -pedantic -Wpointer-arith -Wreturn-type -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wcast-qual -Wextra -o eschalot eschalot.c -lpthread -lssl -lcrypto
eschalot.c:66:10: fatal error: openssl/bn.h: No such file or directory
 #include <openssl/bn.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:45: eschalot] Error 1

**Comment by soguertler** [comment]
You are probably missing the source headers.
Try `sudo apt install openssl libssl-dev`
