### ISSUE TITLE
does not continue after "the-bug"

### ISSUE THREAD

**Issue by drzraf** [ReclaimYourPrivacy/eschalot#4]
Says 

> WARNING! Error detected! CPU/RAM overheating?
> [...]]
> Suspending this thread for 30 seconds.
> Generating new RSA key

but seems stuck. CPU is still at 100%/core, but progress shown on output seems stuck.

**Comment by lbthomsen** [comment]
I've got no idea apart from the original author's comment in the source:

/* Every so often the onion found matches
                                 * whatever we were looking for, but the final
                                 * generated onion is garbage. I suspect a CPU
                                 * or RAM overheating, but it could be a subtle
                                 * bug somewhere. Hard to pin-point. According
                                 * to the reports I've seen, shallot has had a
                                 * similar problem.
                                 *
                                 * Happens most often in a wordlist search mode,
                                 * but I think I have seen it in a regex mode
                                 * as well. Does not seem to happen in a fixed
                                 * prefix mode.
                                 *
                                 * Adding this check to avoid producing garbage
                                 * results and to alleviate the problem a bit. */
