### ISSUE TITLE
CPU/RAM not Overheating

### ISSUE THREAD

**Issue by PeterBeard** [ReclaimYourPrivacy/eschalot#6]
I get this message pretty regularly in prefix mode but my temperatures are all within the normal range (stabilizing around 70-75C). Sometimes the error occurs immediately, sometimes it takes a few minutes. Here's the output of `sensors` after an error (~10 minutes of searching):

    it8728-isa-0a30
    Adapter: ISA adapter
    in0:          +1.03 V  (min =  +2.98 V, max =  +0.11 V)  ALARM
    in1:          +1.52 V  (min =  +1.87 V, max =  +0.97 V)  ALARM
    in2:          +2.86 V  (min =  +0.47 V, max =  +0.86 V)  ALARM
    in3:          +2.80 V  (min =  +2.23 V, max =  +1.60 V)  ALARM
    in4:          +1.07 V  (min =  +1.99 V, max =  +1.82 V)  ALARM
    in5:          +0.01 V  (min =  +1.02 V, max =  +0.19 V)  ALARM
    in6:          +1.07 V  (min =  +1.09 V, max =  +1.82 V)  ALARM
    3VSB:         +3.29 V  (min =  +3.89 V, max =  +1.58 V)  ALARM
    Vbat:         +3.22 V   
    fan1:        2057 RPM  (min =   26 RPM)
    fan2:           0 RPM  (min =   54 RPM)  ALARM
    fan3:           0 RPM  (min =   28 RPM)  ALARM
    temp1:        +71.0°C  (low  = +127.0°C, high = +91.0°C)  sensor = Intel PECI
    temp2:        +29.0°C  (low  =  -1.0°C, high = +127.0°C)  sensor = thermal diode
    temp3:        -70.0°C  (low  =  -1.0°C, high = +127.0°C)  sensor = thermal diode
    intrusion0:  ALARM

    acpitz-virtual-0
    Adapter: Virtual device
    temp1:        +27.8°C  (crit = +105.0°C)
    temp2:        +29.8°C  (crit = +105.0°C)
    temp3:        +71.0°C  (crit = +90.0°C)

    coretemp-isa-0000
    Adapter: ISA adapter
    Physical id 0:  +72.0°C  (high = +93.0°C, crit = +103.0°C)
    Core 0:         +70.0°C  (high = +93.0°C, crit = +103.0°C)
    Core 1:         +72.0°C  (high = +93.0°C, crit = +103.0°C)
    Core 2:         +69.0°C  (high = +93.0°C, crit = +103.0°C)
    Core 3:         +71.0°C  (high = +93.0°C, crit = +103.0°C)

Is it possible something other than overheating is going on? I'm able to run Prime95, etc. on this system for extended periods with no errors so overheating seems unlikely to me. I've collected some of the private keys that triggered this error [here](https://gist.github.com/PeterBeard/1813bf3ad0f0b3ef4dfb370dcba3651f), but I don't see a pattern. I poked around in the source a bit but nothing jumps out at me as wrong. Any idea what could be causing this?

I'm on Debian Testing with kernel 4.8.0, compiled with libssl 1.0.2 and libcrypto 1.0.2

**Comment by lbthomsen** [comment]
First of all - let me stress I didn't write this - just happened to find it and keep track of it here.

Judging from the code it makes no attempt to check any sensors.  There is an error in eschalot.c around line 350 or thereabouts that appear to be a result of some strncmp sanity check.  No idea what would trigger that error.

**Comment by PeterBeard** [comment]
It seems to have stopped happening with libssl 1.1 so maybe it was a problem with the old OpenSSL.

Either way, thanks for following up!
